name: Terraform Plan for Modified Directories

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Identify modified directories
      - name: Identify modified directories
        id: modified_dirs
        run: |
          # List directories with changes in the PR
          git diff --name-only origin/main | awk -F'/' '{
            if ($1 == "workspaces") print $1"/"$2"/"$3"/"$4
          }' | sort -u > modified_dirs.txt
          echo "Modified directories:"
          cat modified_dirs.txt
          # Save modified directories as a JSON array for use in the workflow
          echo "directories=$(cat modified_dirs.txt | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      # Step 3: Terraform Plan for each modified directory
      - name: Run Terraform Plan
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Loop through directories and run plan
        run: |
          for dir in $(echo ${{ env.directories }} | jq -r '.[]'); do
            echo "Running Terraform Plan in $dir"
            cd "$dir"
            terraform init
            terraform plan -out=tfplan
            echo "Plan for $dir:" >> $GITHUB_WORKSPACE/plan_output.txt
            terraform show tfplan >> $GITHUB_WORKSPACE/plan_output.txt
            cd -
          done

      # Step 4: Comment on the PR
      - name: Post Plans to PR
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GT_TOKEN }}
          message: |
            **Terraform Plan Results**
            ```plaintext
            $(cat $GITHUB_WORKSPACE/plan_output.txt)
            ```
