name: Terraform Plan with Python

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Fetch the 'main' branch
      - name: Fetch main branch
        run: git fetch origin main

      # Step 3: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 4: Install dependencies (if needed)
      - name: Install Python dependencies
        run: pip install requests

      # Step 5: Run Python script to identify modified directories
      - name: Identify Modified Directories
        run: python .github/workflows/identify_modified_dirs.py

      # Step 6: Read modified directories and run Terraform Plan
      - name: Run Terraform Plan
        run: |
          touch $GITHUB_WORKSPACE/plan_output.txt
          modified_dirs=$(cat $GITHUB_WORKSPACE/modified_dirs.json | jq -r '.[]')
          for dir in $modified_dirs; do
            echo "Running Terraform Plan in $dir"
            cd "$dir"
            terraform init -input=false
            terraform plan -input=false -out=tfplan
            echo "Plan for $dir:" >> $GITHUB_WORKSPACE/plan_output.txt
            terraform show -no-color tfplan >> $GITHUB_WORKSPACE/plan_output.txt
            cd - > /dev/null
          done

      # Step 7: Comment on the PR
      - name: Post Plans to PR
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            **Terraform Plan Results**
            ```plaintext
            $(cat $GITHUB_WORKSPACE/plan_output.txt)
            ```
