name: 'Atlantis'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write

jobs:
  atlantis:
    name: Atlantis Plan
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/runatlantis/atlantis:v0.23.2-debian
      env:
        ATLANTIS_GH_USER: ${{ github.actor }}
        ATLANTIS_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ATLANTIS_REPO_ALLOWLIST: github.com/${{ github.repository }}
        ATLANTIS_DISABLE_AUTOPLAN: true
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Atlantis
        run: |
          # Start the Atlantis server in the background
          atlantis server &
          atlantis_pid=$!

          # Wait for the server to start
          until curl --output /dev/null --silent --fail http://localhost:4141/healthz; do
            sleep 5
          done

          # Send the GitHub event to Atlantis
          curl --silent --request POST \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Event: ${{ github.event_name }}' \
            --header 'X-GitHub-Delivery: ${{ github.run_id }}' \
            --data '${{ toJson(github.event) }}' \
            http://localhost:4141/events

          # Allow some time for Atlantis to process the event
          sleep 10

          # Stop the server
          kill $atlantis_pid
          wait $atlantis_pid
