name: Pull Request CI for Terraform changes only
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  # We need pull-requests: write to allow the token to write the comments
  pull-requests: write

jobs:
  plan-staging:
    # We need to plan all resources individually because they each have their own plan to send as comment
    name: Plan Terraform Non Prod
    container:
      image: alpine/terragrunt:tf1.9.5
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Plan Terraform Module DB
      uses: './.github/workflows/plan/terragrunt-plan-comment'
      with:
        workdir: config/test1
